name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Emscripten
        uses: mymindstorm/setup-emsdk@v12

      - name: Build Raylib from Source
        run: |
          git clone --depth 1 https://github.com/raysan5/raylib.git
          cd raylib/src
          make PLATFORM=PLATFORM_WEB -e
          cd ../..
          mkdir -p include lib
          cp raylib/src/raylib.h ./include/
          cp raylib/src/libraylib.web.a ./lib/libraylib.a

      - name: Build Web App
        run: |
          emcc main.c vigenere.c -o index.html \
          -I./include -L./lib -lraylib \
          -s USE_GLFW=3 -s ASYNCIFY -DPLATFORM_WEB \
          --shell-file raylib/src/shell.html

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: .
          branch: gh-pages